import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import Navbar2 from "../components/Navebar2";

// import { HeroPage } from "../components/Hero";
// import About from "./about/page";
// import Contact from "./contact/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shuvajit gayen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar2 className="" />
        <Navbar />
        {/* <HeroPage />
        <About />
        <Contact /> */}
        {children}
      </body>
    </html>
  );
}
